sudo: required
dist: trusty
language: python
python:
  - 2.7.11
  - 3.5.1
virtualenv:
  system_site_package: true

install:
  - echo $TRAVIS_PYTHON_VERSION
  - pip install -U -r ./requirements.txt
  - pip install tensorflow
  - wget https://www.dropbox.com/s/cd0drt6t9q1mwg0/deeplab_resnet.ckpt?dl=1 -O deeplab_resnet.ckpt
  
script:
  - python inference.py ./images/summary.png ./deeplab_resnet.ckpt
