sudo: required
dist: trusty
language: python
python:
  - 2.7.11
  - 3.5.1
virtualenv:
  system_site_package: true

install:
  - echo $TRAVIS_PYTHON_VERSION
  - pip install -U -r ./requirements.txt
  - pip install tensorflow
